### ISSUE TITLE
make m_iobuf adjustable

### ISSUE THREAD

**Issue by fdistorted** [OPEnSLab-OSU/SSLClient#24]
**Is your feature request related to a problem? Please describe.**
That would be great to make `m_iobuf` adjustable without changing the library code.

**Describe the solution you'd like**
It can be done by defining a buffer size using `#define` or via making `m_iobuf` declared in dynamic way. Which way is better?

**Comment by prototypicalpro** [comment]
A `#define` in the sketch would work in a standard C++ project, however the Arduino IDE chooses to compile libraries individually and link everything together when finished--this process allows the IDE to cache compiled dependencies on a per-file basis, speeding up the entire compilation process. Because of this isolation, however, a `#define` macro in the sketch will be processed until _after_ SSLClient has already been compiled, resulting in the setting being ignored. This problem is explored more in an [Arduino Forum post](https://forum.arduino.cc/index.php?topic=92382.0).

I have considered making `m_iobuf` dynamically allocated, as this is the approach taken by both the ESP8266 and ESP32 `WiFiClientSecure` implementation. My primary concern is with lower-power microcontrollers such as the SAMD21: as these processors do not have very much memory, it is advantageous to allocate as much memory on the stack as possible, preventing reliability issues such as heap fragmentation. As my primary use case for SSLClient with these low-memory devices, I'd like to keep `m_iobuf` off the heap for now.

C++ does provide one other method of providing a compile-time constant without using `#define` (that I've found anyway): class templates. A possible solution to this problem would be to template the entire SSLClient class with the buffer length:
```C++
template<size_t buffer_length>
class SSLClient : public Client {
  // ...
  unsigned char m_iobuf[buffer_length];
}
```
The trouble with class templates is they require all of the member implementations to also be templated:
```C++
template<size_t b>
void SSLClient<b>::do_something() { /* ... */ }
```
Because of this, the _entire_ implementation of SSLClient must be in header files instead of source files. As there is nothing to "compile" in a header-only library, the Arduino IDE can no longer cache it, and compilation time increases dramatically. This restriction makes class templates unwieldy to work with, and as a result I've left SSLClient untemplated for now.

Given the above options, I think manually modifying the library is the best compromise (despite being a bit clunky). I'd be happy to review a PR suggesting a better solution, but for the reasons stated above I'm going to leave it for now.
